// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpqjuxgakhrkldjsrhwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcWp1eGdha2hya2xkanNyaHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjA1OTcsImV4cCI6MjA3NDYzNjU5N30.WnN2C8_lWplmM2fVELabQYXhWKjp6zTyYP5VcDRARZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});